export const EMPTY_STRING = '';
export const MAX_PASSWORD_LENGTH = 7;
export const ERROR_INPUT_MESSAGE = 'Field is required!';
export const BACK = -1;
export const ONE = 1;
export const DELAY = 500;
export const ZERO = 0;
export const TWO = 2;
export const MAX_CARDS_COUNT = 150;
